### ISSUE TITLE
[feature] Add `permissions-config` repository support

### ISSUE THREAD

**Issue by Nkmol** [DrFaust92/terraform-provider-bitbucket#109]
### References
- https://developer.atlassian.com/cloud/bitbucket/new-repo-permission-apis/
- https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-permissions-config-groups-group-slug-put

---

I am open to pick this up whenever I have some time.

**Comment by DrFaust92** [comment]
will try to look into this as well
