### ISSUE TITLE
bitbucket_default_reviewers throwing 400

### ISSUE THREAD

**Issue by quentin9696** [DrFaust92/terraform-provider-bitbucket#122]
Hi,

### Terraform Version
```
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/drfaust92/bitbucket v2.24.0
```

### Affected Resource(s)
- bitbucket_default_reviewers

### Terraform Configuration Files
```hcl
resource "bitbucket_default_reviewers" "this" {
  owner      = <my_owner>
  repository = bitbucket_repository.this.name

  reviewers = <my list of users uuid>
}
```

### Debug Output

When apply, the plan show me the diff but when apply I got a 400 bad request
```
# module.repository["bash-acms-anonymization-scripts"].bitbucket_default_reviewers.this will be created
  + resource "bitbucket_default_reviewers" "this" {
      + id         = (known after apply)
      + owner      = MASKED
      + repository = MASKED
      + reviewers  = [
          + "{MASKED UUID}"
    }
```

### Expected Behavior
I should apply the correct configuration

### Actual Behavior
Run a 400 bad request

### Steps to Reproduce
1. `terraform apply`

**Comment by DrFaust92** [comment]
hi @quentin9696 i cannot reproduce this and tests are passing. can you check you have the proper permissions and are passing the right params?

**Comment by DrFaust92** [comment]
`owner` should the workspace name
