### ISSUE TITLE
Feature: Adding repos to groups

### ISSUE THREAD

**Issue by mkohn** [DrFaust92/terraform-provider-bitbucket#130]
I would like the ability to add repository to groups.

**Comment by DrFaust92** [comment]
unless @mkohn can elaborate i think this is duplicate of https://github.com/DrFaust92/terraform-provider-bitbucket/issues/109

**Comment by mkohn** [comment]
Sorry you are correct I missed that when I looked through the issues. We should close this as a duplicate.

**Comment by DrFaust92** [comment]
[mkohn](https://github.com/mkohn) added in 2.28.0 version
