### ISSUE TITLE
Incorrect Docs Example

### ISSUE THREAD

**Issue by AlmogCohen** [DrFaust92/terraform-provider-bitbucket#144]
As can be seen in the official docs here: https://registry.terraform.io/providers/DrFaust92/bitbucket/latest/docs/resources/deployment_variable

The example `name` and this is not a valid option - `key` should be used instead. Incorrect docs:
```
resource "bitbucket_deployment_variable" "country" {
  deployment = bitbucket_deployment.test.id
  name       = "COUNTRY"
  value      = "Kenya"
  secured    = false
}
```

### Affected Resource(s)
- bitbucket_deployment_variable

**Comment by DrFaust92** [comment]
fixed
