### ISSUE TITLE
produced an unexpected new value: Root resource was present, but now absent.

### ISSUE THREAD

**Issue by eyalya** [DrFaust92/terraform-provider-bitbucket#145]
Hi there,
I am using latest terraform version. 
the resource affected is bitbucket_deployment_variable. 
I am deploying and it create the following error code:
`When applying changes to module.******[0].bitbucket_deployment_variable.this["*****"],
│ provider "provider[\"registry.terraform.io/drfaust92/bitbucket\"]" produced an unexpected new value: Root resource was present,
│ but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

I am deploying more than 60 variables to the same deployment. I assume it connected to that.

**Comment by DrFaust92** [comment]
@eyalya yeah the high amount of vars probably not being paginated well. ill take a look

**Comment by eyalya** [comment]
Any update?

**Comment by DrFaust92** [comment]
Closing as duplicate of https://github.com/DrFaust92/terraform-provider-bitbucket/issues/164
