### ISSUE TITLE
New Feature Request - Project level permissions

### ISSUE THREAD

**Issue by MathewHD** [DrFaust92/terraform-provider-bitbucket#160]
Hi there,

It seems that Atlassian has added project level permissions to the bitbucket UI, https://support.atlassian.com/bitbucket-cloud/docs/configure-project-permissions-for-users-and-groups/. These features do not appear to be on their API yet. Once the API does support adding / modifying / deleting these level of permissions could you add them to your terraform provider?

BTW thank you very much for stepping in here and providing the Terraform provider Atlassian is unwilling to create.

**Comment by DrFaust92** [comment]
seems to be available. will start taking a look

**Comment by DrFaust92** [comment]
seems ive implemented this and forgot, closing

**Comment by DrFaust92** [comment]
was wrong, it was repo level
