### ISSUE TITLE
Feature request. Get deployments withoud uuid

### ISSUE THREAD

**Issue by bartje321** [DrFaust92/terraform-provider-bitbucket#162]
Hi there,

Thank you for your amazing work on this provider.

I'm working with this but I ran into the problem I don't have a good way to access deployments.
I want to set deployment variables on the default production 
```
resource "bitbucket_deployment_variable" "my_secret" {
  deployment = <deployment id here>
  key = "MY_SECRET"
  value = "VALUE"
  secured = true
}
```

But to get the necessary id is by fetching the deployment (as this is a default one created by BitBucket)

```
data "bitbucket_deployment" "example" {
  uuid       = <this is hard>
  repository = bitbucket_repository.repository.id
  workspace  = var.workspace.slug
}
```

The problem I have is it's hard to find the uuid of the existing deployment, and with a lot of repos (300+) this will be a lot to configure. It whould be really beneficial if there is a way to fetch existing deployments by workspace, repo and name. Or list all deployments by just workspace and repo

For example;
```
data "bitbucket_deployment" "production" {
  name = "Production"
  repository = bitbucket_repository.repository.id
  workspace  = var.workspace.slug
}
```
or
```
data "bitbucket_deployments" "deployments" {
  repository = bitbucket_repository.repository.id
  workspace  = var.workspace.slug
}
```

**Comment by giveadamakick** [comment]
I'm also facing the same problem as @bartje321.

Fetching all deployments for a particular repo and workspace is possible via this endpoint in the REST API: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-deployments/#api-repositories-workspace-repo-slug-deployments-get

So the proposed solution should technically be possible.

**Comment by DrFaust92** [comment]
I think this requires a dedicated data source that fetches all of the deployments (and users will filter on their end with some for)
