### ISSUE TITLE
Feature request: add `deletion_protection` flag to `bitbucket_repository`

### ISSUE THREAD

**Issue by redzioch** [DrFaust92/terraform-provider-bitbucket#214]
As we all know, loosing a repository can be a great disaster, sometimes larger than loosing part of infrastructure.

It would be great to have flag securing repositories from accidental destroy.

Such flags are used in other providers eg. Google - it should work in the same way here.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#deletion_protection

> `deletion_protection` - (Optional) Whether Terraform will be prevented from destroying the instance. When the field is set to true or unset in Terraform state, a terraform apply or terraform destroy that would delete the instance will fail. When the field is set to false, deleting the instance is allowed.

**Comment by DrFaust92** [comment]
Hi @redzioch, you can use native TF feature for this https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#prevent_destroy

**Comment by redzioch** [comment]
Wow, thank you. You learn new things everyday, indeed.

**Comment by dobeerman** [comment]
Unfortunately, not for all resources this native TF feature works. For instance, neither for bitbucket_deployment, nor bitbucket_deployment_variable.

Is there any way to prevent deletion for those resources as it might be quite sensitive.
