### ISSUE TITLE
Branching model always shows changes in plan when using "use_mainbranch" 

### ISSUE THREAD

**Issue by tobiaskloss** [DrFaust92/terraform-provider-bitbucket#23]
When using the branching model resource it seems that the plan always shows a change when using `"use_mainbranch": true`

### Terraform Version
1.1.4

### Affected Resource(s)
- bitbucket_branching_model

### Terraform Configuration Files
In JSON-Format as generated by Terraform CDK
```json
"bitbucket_branching_model": {
      "template-repository_branch-model": {
        "owner": "xyz",
        "repository": "xyz",
        "branch_type": [
          {
            "enabled": true,
            "kind": "bugfix",
            "prefix": "bugfix/"
          },
          {
            "enabled": true,
            "kind": "feature",
            "prefix": "feature/"
          },
          {
            "enabled": true,
            "kind": "hotfix",
            "prefix": "hotfix/"
          },
          {
            "enabled": true,
            "kind": "release",
            "prefix": "release/"
          }
        ],
        "development": {
          "use_mainbranch": true
        }
      }
}
```

### Expected Behavior
The plan should be empty

### Actual Behavior
The plan shows that the development branch will be changed

### Steps to Reproduce
1. Create repository with the branching model above and `terraform apply`

### Important Factoids
We're using the Terraform CDK

### References
None

**Comment by DrFaust92** [comment]
Ill take a look this resource was tricky

**Comment by DrFaust92** [comment]
Hi @tobiaskloss, i cant replicate this at the latest version of the provider.

**Comment by tobiaskloss** [comment]
I'll update to the latest Version and provide feedback from my side.

**Comment by tobiaskloss** [comment]
Hi @DrFaust92 ,

couldn't reproduce the error with the recent version.
