### ISSUE TITLE
Link in 'About' section on main page of repo links to the Terraform registry this repo was forked from.

### ISSUE THREAD

**Issue by mjourardssg** [DrFaust92/terraform-provider-bitbucket#26]
Hi there,

It looks like the front page of this repo links back to aeirola's Terraform registry entry, when it should be linking here: https://registry.terraform.io/providers/DrFaust92/bitbucket/latest

Ngl, this gave me pause to use your provider, but if this is the most maintained one I'll likely still use this.

**Comment by DrFaust92** [comment]
Thanks, will update links. was focusing on functionality 🥲

**Comment by DrFaust92** [comment]
fixed, thanks for pointing out. @mjourardssg
