### ISSUE TITLE
bitbucket_branch_restriction doesn't honour http 404 any more.

### ISSUE THREAD

**Issue by jimmyR** [DrFaust92/terraform-provider-bitbucket#52]
### Terraform Version
Terraform v1.0.4
on darwin_amd64
 provider registry.terraform.io/DrFaust92/bitbucket v2.13.1

### Affected Resource(s)
bitbucket_branch_restriction

### Terraform Configuration Files
```hcl
resource "bitbucket_branch_restriction" "foo_reset_pullrequest_approvals_on_change" {
  owner      = "foo"
  repository = bitbucket_repository.foo.name
  kind = "reset_pullrequest_approvals_on_change"
  pattern = "main"
}
```

### Expected Behavior
When a branch restriction is removed behind terraform's back, it's expected that provider would handle the ensuing HTTP404, and recreate the resource.

### Actual Behavior
When a branch restriction is removed behind terraform's back, terraform throws a persistent error:

```
 Error: 404 Not Found
 
   with bitbucket_branch_restriction.foo_reset_pullrequest_approvals_on_change,
   on main.tf line 80, in resource "bitbucket_branch_restriction" "foo_reset_pullrequest_approvals_on_change":
   80: resource "bitbucket_branch_restriction" "foo_reset_pullrequest_approvals_on_change" {
```
This error appears to be unrecoverable.

### Steps to Reproduce
Create a branch restriction on any repo in bitbucket

Apply the change using terraform

Remove the branch restriction in the bitbucket web interface

Apply the config using terraform once again

### Important Factoids
This seems to be caused by the following code:
```
	brRes, res, err := brApi.RepositoriesWorkspaceRepoSlugBranchRestrictionsIdGet(c.AuthContext, url.PathEscape(d.Id()),
		d.Get("repository").(string), d.Get("owner").(string))

	if err != nil {
		return diag.FromErr(err)
	}

	if res.StatusCode == 404 {
		log.Printf("[WARN] Branch Restrictions (%s) not found, removing from state", d.Id())
		d.SetId("")
		return nil
	}
```
Since brApi.RepositoriesWorkspaceRepoSlugBranchRestrictionsIdGet now returns an error condition on 404, the 404 handling code never gets a chance to execute anymore

```
	resp, err := c.HTTPClient.Do(req)
	log.Printf("[DEBUG] Resp: %v Err: %v", resp, err)
	if resp.StatusCode >= 400 || resp.StatusCode < 200 {
		apiError := Error{
			StatusCode: resp.StatusCode,
			Endpoint:   endpoint,
		}
```

### Potential Solution
I've used this
```
        if res.StatusCode == 404 {
                log.Printf("[WARN] Branch Restrictions (%s) not found, removing from state", d.Id())
                d.SetId("")
                return nil
        } else if err != nil {
                return diag.FromErr(err)
        }
```
However, this seem folly to check the error status only after checking the status code for 404.

**Comment by zelch** [comment]
Any update on this?  It is definitely a significant issue preventing us from moving to a current version of this provider.
