### ISSUE TITLE
bitbucket_branch_restriction doesn't handle "groups" changes properly for "restrict_merges"

### ISSUE THREAD

**Issue by blbradley** [DrFaust92/terraform-provider-bitbucket#58]
### Terraform Version
Terraform v0.13.7
+ provider registry.terraform.io/drfaust92/bitbucket v2.4.1
+ provider registry.terraform.io/hashicorp/aws v3.75.1

### Affected Resource(s)
Please list the resources as a list, for example:
resource "bitbucket_branch_restriction" "kaena1_repo_restrict_merges" {
  kind       = "restrict_merges"
}

### Terraform Configuration Files
```hcl
resource "bitbucket_branch_restriction" "owner_repo_restrict_merges" {
  for_each   = local.repos
  repository = each.value
  owner      = "owner"
  kind       = "restrict_merges"
  pattern    = "master"
  
  users = [
    "username",
  ]
  
  groups = [
  ]
}
```

### Expected Behavior
no error

### Actual Behavior

```
Error: Unsupported argument

  on repos.tf line 210, in resource "bitbucket_branch_restriction" "kaena1_repo_restrict_merges":
 210:   groups = [

An argument named "groups" is not expected here. Did you mean to define a
block of type "groups"?
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by DrFaust92** [comment]
ill try take a closer look soon.

**Comment by jdivine** [comment]
I had the same error.  Found this thread then looked at the code.  Turns out that I was able to create groups using a block syntax.

`dynamic "groups" {
    for_each = var.groups

    content {
      slug = each.value
      owner      = bitbucket_repository.repo.owner
    }
  }`

**Comment by blbradley** [comment]
@jdivine thanks for your response ✨

do you know what that looks like with a regular non-dynamic block?

**Comment by jdivine** [comment]
@blbradley Sure .. this seems to work

```
  groups {
    slug = "my-group"
    owner      = "my-owner"
  }
```

And multiple groups blocks can be specified.
