### ISSUE TITLE
Current user getting 403

### ISSUE THREAD

**Issue by ebertti** [DrFaust92/terraform-provider-bitbucket#59]
Hi there,

I am getting a error trying do get information from current user that is running the terraform.

### Terraform Version

Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/drfaust92/bitbucket v2.14.0

Your version of Terraform is out of date! The latest version
is 1.1.8. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

data bitbucket_current_user

### Terraform Configuration Files
```hcl
data "bitbucket_workspace" "xxxxx" {
  workspace = "xxxxx"
}

data "bitbucket_current_user" "user" {

}
```

### Debug Output

│ Error: error reading current user: 403 Forbidden
│ 
│   with data.bitbucket_current_user.user,
│   on workspace.tf line 5, in data "bitbucket_current_user" "user":
│    5: data "bitbucket_current_user" "user" {

**Comment by DrFaust92** [comment]
Seems to be a permissions issue so im unsure how this is a bug in the provider.

**Comment by DrFaust92** [comment]
Closing for lack of response, if issue persists please re-open with more details.
