### ISSUE TITLE
Importing existing bitbucket repository fails with 403 Forbidden

### ISSUE THREAD

**Issue by JohnKibe** [DrFaust92/terraform-provider-bitbucket#62]
### Terraform Version
Terraform v1.1.9
provider.bitbucket v2.13.1

### Affected Resource(s)

terraform import repository

### Terraform Configuration Files

provider "bitbucket" {
username = "xxxxxx"
password = var.password
}

resource "bitbucket_repository" "xxxxxx {
  owner           = "xxxxxx"
  name           = "xxxxxx"
  has_wiki      = false
  is_private    = true
  scm             = "git"
  fork_policy  = "no_public_forks"
  has_issues = false
  slug             = "xxxxxx"
  pipelines_enabled = true
}

then did
terraform import module.xxx.module.repositories.bitbucket_repository.xxxxxx "xxxxxxxxx/xxxxxx"

### Expected Behavior
Successful import of the existing resource

### Actual Behavior
Output of terraform import
module.xxx.module.repositories.bitbucket_repository.xxxxxx: Import prepared!
module.xxx.module.repositories.bitbucket_repository.xxxxxx: Refreshing state... [id=xxxxxxxxx/xxxxxx]
│ Error: error reading repository (xxxxxxxxx/xxxxxx): 403 Forbidden

### More information
User has admin permissions and the app passwords has admin privileges as well. It works on all resources except terraform import.

### Thank You

**Comment by DrFaust92** [comment]
As long as the import uses `owner/slug` the issue does not seem related to provider but to credentials. unless you can provide more logs to show is with the provider im closing this. feel free to re-open with more details as im unable to recreate this issue.
