### ISSUE TITLE
Feature: Merge checks / conditions

### ISSUE THREAD

**Issue by PerWiklander** [DrFaust92/terraform-provider-bitbucket#65]
I couldn't see anything about merge checks / conditions in the docs.

![branch-permissions-merge-checks](https://user-images.githubusercontent.com/391989/167243774-f841e034-e795-43f0-8147-3e9c27169dd2.png)

**Comment by PerWiklander** [comment]
My bad, it's the `kind` attribute.
Like
```
“kind”: “require_passing_builds_to_merge”,
```

Atlassians docs kinda suck here though, they don't list the available types.
Maybe list them in your docs to help users?

If anyone else has the same problem, I pulled these out of the HTML of the bitbucket settings page:

```
allow_auto_merge_when_builds_pass
require_passing_builds_to_merge
require_default_reviewer_approvals_to_merge
require_approvals_to_merge
require_no_changes_requested
require_tasks_to_be_completed
enforce_merge_checks
force
delete
restrict_merges
push
```

**Comment by PerWiklander** [comment]
Ok, I'll make sure to bring a rubber duck to the office next time so I don't have to do the whole "debugging by writing a Github issue" dance :-)

**Comment by justmiles** [comment]
For what it's worth, I found this very helpful. Thanks for rubber-ducking out loud for the rest of us.
