### ISSUE TITLE
Importing bitbucket_deployment is not supported

### ISSUE THREAD

**Issue by ilons** [DrFaust92/terraform-provider-bitbucket#79]
**Feature Request**: Support importing deployments

Thank you for putting the time in to keep this provider alive!

### Terraform Version
1.2.3

### Affected Resource(s)
- bitbucket_deployment

### Terraform Configuration Files

resource "bitbucket_deployment" "cms-staging" {
  name = "cms-staging"
  repository = var.bitbucket_repo
  stage = "Staging"
}

### Expected Behavior
The deployment resource is imported into state

### Actual Behavior
I get a message that  the resource does not support importing:
`Error: resource bitbucket_deployment doesn't support import`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import bitbucket_deployment cms-staging "my/repo:{<deployment uuid>}" `

**Comment by alaminopu** [comment]
It should also support importing deployment variables.
