### ISSUE TITLE
Deployments Datasource

### ISSUE THREAD

**Issue by tbpoetke** [DrFaust92/terraform-provider-bitbucket#87]
Hi there,

thanks for developing this provider! 
I want to ask, if it's possible to add an datasource for deployments?
Since there is no datasource I have a chicken-egg problem, I cant push my Terraform code with a bitbucketpipeline, which contains a deployment, which will be created by Terraform.
On the other side, I'm not allowed to write vars in an existing deployment.
Bitbucket API documentation looks like it's possible:
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-deployments/#api-repositories-workspace-repo-slug-deployments-get

I don't have knowledge in Go/Terraform provider, so I cant really help ....

**Comment by tobiaskloss** [comment]
We ran into this issue as well today - we want to switch from repository to deployment variables to boil down the steps in our pipelines.

**Comment by DrFaust92** [comment]
will look into this

**Comment by DrFaust92** [comment]
@tobiaskloss / @tbpoetke opened #133 please LMK if this what you had in mind. if not please open another ticket with requested resource and iil work on it

**Comment by tobiaskloss** [comment]
@DrFaust92 #133 seems to address exactly what I had in mind!
