### ISSUE TITLE
Support for multiple workspaces?

### ISSUE THREAD

**Issue by raypettersen** [DrFaust92/terraform-provider-bitbucket#89]
I'm trying out this provider, and trying to create a project. However, the project resource does not have "workspace" as input. Attempts at creating a workspace fails, and I'm assuming it's because I'm unable to set the workspace in question. How else would the provider know which workspace I'd like to create my project in?

**Comment by vtr-rivia** [comment]
I'm facing the same problem here. 

First I've tried with user as owner
`
data "bitbucket_current_user" "bitbucket_user" {}

resource "bitbucket_project" "devops" {
  owner = data.bitbucket_current_user.bitbucket_user.username
  name  = "Medex DevOps"
  key = "DEVOPS"
}
`

The error is: **Error: error creating project (DEVOPS): 404 Not Found**

After that, I've tried with the group name on resource
`
resource "bitbucket_project" "devops" {
  owner = "administrators"
  name  = "Medex DevOps"
  key = "DEVOPS"
}
`

The error is **Error: error creating project (DEVOPS): 403 Forbidden**

**Comment by DrFaust92** [comment]
owner field is legacy leftover and should be treated as workspace
