### ISSUE TITLE
400 error when creating projects in version 2.21.2 (works in 2.20.0)

### ISSUE THREAD

**Issue by dejoost** [DrFaust92/terraform-provider-bitbucket#90]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.3.0

### Affected Resource(s)
bitbucket_project

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl



terraform {
  required_providers {
    bitbucket = {
      source = "DrFaust92/bitbucket"
      version = "2.21.2"
    }
  }
}

provider "bitbucket" {
  # Configuration options
}

resource "bitbucket_project" "test" {
  owner  = "myteam" # must be a team
  name   = "illusions-project"
  key    = "ILLUSIONSPROJ"
  is_private = true
  description = "whatever"
}
```

### Debug Output
https://gist.github.com/dejoost/94bfcbea0a1ac4e4aa73046a1bee29d6

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
project created

### Actual Behavior
not created with error:
```
│ Error: error creating project (ILLUSIONSPROJ): 400 Bad Request
│ 
│   with bitbucket_project.test,
│   on main.tf line 24, in resource "bitbucket_project" "test":
│   24: resource "bitbucket_project" "test" {
│ 
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
this is working as expected in 2.20.0, seems a regression error

**Comment by JustinJohnWilliams** [comment]
Same thing is happening for me as well. Can confirm `2.20.0` successfully creates projects.

**Comment by DrFaust92** [comment]
i am able to reproduce, checking

**Comment by DrFaust92** [comment]
v2.21.3 released. testing locally showed this to be working after fix
